im:
  tcpPort: 9000
  webSocketPort: 19000
  bossThreadSize: 1
  workThreadSize: 8
  heartBeatTime: 3000
  brokerId: 1000    #服务节点id
  loginModel: 1
  logicUrl: http://localhost:8000/v1

  redis:
    mode: single
    database: 0
    password: asdfghjkl123
    timeout: 3000
    poolMinIdle: 8
    poolConnTimeout: 3000
    poolSize: 10
    single:
      address: 162.14.106.166:6379

  rabbitmq:
    host: 162.14.106.166
    port: 5672
    virtualHost: im
    userName: myf
    password: 123

  zkConfig:
    zkAddr: 162.14.106.166:2181
    zkConnectTimeOut: 15000